package com.acme;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;

/**
 * Standard main class for Spring, generated by Spring template
 */
@SpringBootApplication
@ComponentScan
public class Application {
    private static ApplicationContext applicationContext;
    public static void main(String[] args) {

        SpringApplication.run(Application.class, args);

    }

    public static ApplicationContext getApplicationContext()
    {
        return new AnnotationConfigApplicationContext(Application.class);
    }

}