package com.acme;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

/**
 * Standard main class for Spring, generated by Spring template
 */
@SpringBootApplication
//@ComponentScan  // Not needed: SpringBootApplication AND at top of package hierarchy
public class Application {
    /**
     * Maintain a reference to Spring's 'context' for our application.
     */
    private static ApplicationContext applicationContext;
    public static void main(String[] args) {
        applicationContext = new AnnotationConfigApplicationContext(Application.class);
        SpringApplication.run(Application.class, args);
    }

    /**
     * Obtain reference to Spring's 'context' for our application.
     * @return
     */
    public static ApplicationContext getApplicationContext()
    {
        return applicationContext;
    }

}